FROM maven:3.8.5-openjdk-11 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM openjdk:11-jre-slim
WORKDIR /app
COPY --from=build /app/target/FlightSearchService-0.0.1-SNAPSHOT.jar /app/FlightSearchService.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "FlightSearchService.jar"]
